#!/bin/bash
#SBATCH -J loo-mpi
#SBATCH -p skx
#SBATCH -N 1
#SBATCH --ntasks-per-node 14
#SBATCH --job-name=LooMF
#SBATCH --time=10:00:00
#SBATCH --output=%x-%j.out

hostname; pwd; date

# Set OMP_NUM_THREADS to the number of allocated CPUs per task
#export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OMP_NUM_THREADS=1

ibrun -n 14 python run_loo_mf_hmf.py