#!/bin/bash
#SBATCH -p skx
#SBATCH -N 1
#SBATCH --ntasks-per-node 24
#SBATCH --job-name=fp-4
#SBATCH --time=6:00:00
#SBATCH --output=%x-%j.out

hostname; pwd; date


ibrun python test_corr_fof.py --stat 'corr' --fp_frac 0.1 --save_file 'wp_fof_uniform_10_percent_cosmo_10p_Box250_Part750_0000.hdf5'