#!/bin/bash
#SBATCH -J wide
#SBATCH -p skx-dev
#SBATCH -N 1
#SBATCH --ntasks-per-node 13
#SBATCH --cpus-per-task 1
#SBATCH --time=10:00:00
#SBATCH --output=%x-%j.out

hostname; pwd; date

# Set OMP_NUM_THREADS to the number of allocated CPUs per task
#export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK


ibrun -n 24 python test_Astrid.py --type fof
