#!/bin/bash
#SBATCH -J corr_pigs
#SBATCH -p skx
#SBATCH -N 4
#SBATCH --ntasks-per-node 48
#SBATCH --job-name=Wp-HF
#SBATCH --time=4:00:00
#SBATCH --output=%x-%j.out

hostname; pwd; date

BASEDIR='/scratch/06536/qezlou/Goku/FOF/L2'
SAVEDIR='/scratch/06536/qezlou/Goku/processed_data/fft_corr/1d/'

ibrun python get_corr.py --ranks_for_nbkit 24 --base_dir $BASEDIR --z 2.5 --logging_level 'DEBUG' --stat 'corr' --mode '1d' --fft_model 1 --savedir $SAVEDIR --realizations 100
