#!/bin/bash
#SBATCH -J corr_pigs
#SBATCH -p skx
#SBATCH -N 4
#SBATCH --ntasks-per-node 48
#SBATCH --job-name=Wp-HF
#SBATCH --time=4:00:00
#SBATCH --output=%x-%j.out

hostname; pwd; date

BASEDIR='/scratch/06536/qezlou/Goku/FOF/HF'
SAVEDIR='/scratch/06536/qezlou/Goku/processed_data/corr_projected/'

ibrun python get_corr.py --ranks_for_nbkit 24 --base_dir $BASEDIR --z 2.5 --logging_level INFO --stat 'corr' --mode 'projected' --savedir $SAVEDIR
