#!/bin/bash
#SBATCH -p skx
#SBATCH -N 1
#SBATCH --ntasks-per-node 24
#SBATCH --job-name=test_pow
#SBATCH --time=20:00:00
#SBATCH --output=%x-%j.out

hostname; pwd; date

BASEDIR='/scratch/06536/qezlou/Goku/FOF/L1'


ibrun python test_pk.py

