#!/bin/bash
#SBATCH -p skx
#SBATCH -N 8
#SBATCH --ntasks-per-node 48
#SBATCH --job-name=fofHF74
#SBATCH --time=24:00:00
#SBATCH --output=%x-%j.out

hostname; pwd; date

BASEDIR='/scratch/06536/qezlou/Goku/FOF/L1'


ibrun python test_corr_fof.py

